spring.datasource.url=jdbc:hsqldb:mem:scrambledb
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.hsqldb.jdbcDriver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

spring.jpa.properties.hibernate.default_schema=SCRAMBLE
